### ISSUE TITLE
Add section for Game Nights (HGN and AUGN)

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#13]
P2P Hack Club runs two game nights, Hypixel Game Night and Among Us Game Night. (information for these game nights are on https://augn.p2phack.club and https://hgn.p2phack.club). It would be really cool to have a Minecraft/Among Us advertisement section on the main page of the site linking directly to the two websites above, with general information about game nights. This should also include a link to our discord server (for now, just link to https://p2phack.club/discord, even if it is a 404 page. Will be fixed in #14).

**Adding this feature would consist of:**
1. Creating a section on the main page of the website linking to https://hgn.p2phack.club and https://augn.p2phack.club
2. Adding some cool images or design features to highlight the events
3. Linking to our discord server, at https://p2phack.club/discord

**Resources:**
* https://2020.p2phack.club/discord
* https://augn.p2phack.club
* https://hgn.p2phack.club

---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by arialdyscv** [comment]
@thatrobotdev Hello, may i work on this? :)

**Comment by bharmalh** [comment]
@thatrobotdev Please may I work on this? I would love to work on this.

**Comment by thatrobotdev** [comment]
Hey @arialdyscv, yes, you can work on this! Sorry @bharmalh, but I would be really grateful if you could work on any other open issues looking for contributors!

Thank you so much :D

**Comment by thatrobotdev** [comment]
Closed per #48! :D
