### ISSUE TITLE
Add live Hacktoberfest PR Counter to site footer

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#15]
![GitHub Hacktoberfest combined status](https://img.shields.io/github/hacktoberfest/2021/P2PHackClub/website) <-- this is super cool!

On our website, it would be even cooler 😎 

Your task, if you should choose to accept it, is to embed this badge into the footer, to help increase awareness of our Hacktoberfest project on the site! If it works better somewhere else on the site (like in the events section, or the navbar) feel free to add it there instead!

**Resources**
- Badge source: https://img.shields.io/github/hacktoberfest/2021/P2PHackClub/website
---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by saurabhan** [comment]
Can I work on this?

**Comment by saurabhan** [comment]
@thatrobotdev I have created a PR please check.
