### ISSUE TITLE
Add styling for font in the Hacktoberfest description 

### ISSUE THREAD

**Issue by bear217** [P2PHackClub/website#18]
Currently the font for the description of what Hacktoberfest is is looking a little, well, boring. Change the font to something that fits with the rest of the page, and style it with colors and whatnot to something that you feels fits! 
![image](https://user-images.githubusercontent.com/71842478/136592870-63072c29-262b-465e-91c5-24c18396be13.png)

**Comment by arialdyscv** [comment]
@bear217 Hello, may i work on this for hacktoberfest? :)

**Comment by bear217** [comment]
Issue was adressed and fixed!
