### ISSUE TITLE
Add a slideshow containing pictures relevant to peak to peak hack club! 

### ISSUE THREAD

**Issue by bear217** [P2PHackClub/website#22]
Our older site contained a photo slideshow that could be used for announcement/event images, or images from/in the club as a whole. We want to replicate this on our site! Create and stylize a slideshow function into the page using whatever you feel is best fit, and then add placeholder images that can be swapped out for images from the club!

**Comment by S3cBar0n** [comment]
See PR #25

**Comment by thatrobotdev** [comment]
u da best @S3cBar0n :D
