### ISSUE TITLE
Dino plop

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#29]
![Image of a dino saying hi](https://user-images.githubusercontent.com/18013689/136740312-750a448c-29c3-455d-9bb6-c6de18d68d12.png)

Hello! Our official mascot is our lord and savior Orpheus, the dino, who is actually the best mascot in existence.

![Dino with a crown](https://user-images.githubusercontent.com/18013689/136740459-4b2cee2b-e49c-4dc7-8d5c-8042bb690d93.png)

If we can stick Orpheus literally everywhere on the website that still makes it practically useful, we can show a little mascot pride :D.

![Code Dino](https://user-images.githubusercontent.com/18013689/136740598-1e8b5713-2ad8-475e-9b03-2475b4a0aab0.png)

The repository https://github.com/hackclub/dinosaurs has soooooooooo many images for use, so feel free to use the most topical dino available! 

**Required (not really lol) reading about our lord and savior:** https://workshops.hackclub.com/orpheus/

---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by johanvanderkuijl** [comment]
I would like to work on this one

**Comment by thatrobotdev** [comment]
Closed per #49 :D :D :D
