### ISSUE TITLE
Adding navigation bar

### ISSUE THREAD

**Issue by user23ayush** [P2PHackClub/website#30]
The website needs a navigation bar. I am ready to contribute. Kindly assign me this issue

**Comment by S3cBar0n** [comment]
Hey @user23ayush!

We already have a "nav bar" of sorts, you can find that as div with the gridcontainer class. 

What kind of nav bar are you hoping to add? Will this be in addition to the existing one or just a stylistic update for the current?


Just trying to help you avoid unnecessary work.

Thanks!
S3cBar0n
