### ISSUE TITLE
Logo timeeee

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#36]
Time for a logo! No, [not the programming language](https://en.wikipedia.org/wiki/Logo_(programming_language)), we should add our programming club logo to the website!

![P2P Hack Club](https://user-images.githubusercontent.com/18013689/136882994-f858fd83-b29b-4992-be1d-6790b007959b.png)

Preferably, we should put it at one of these 3 places, whichever makes the most sense with the size of the logo and how much it pushes content in the rest of the website.

![Image of annotated website](https://user-images.githubusercontent.com/18013689/136883163-24177922-6940-4378-b65b-6c13560920ca.png)

We also might want to add the logo in the footer, but play around with it! This is how we had an old design of our website:

![Screenshot of old website](https://user-images.githubusercontent.com/18013689/136883322-cb39cd50-88b3-4caa-9902-f770c23af027.png)

---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by rasmita404** [comment]
Hey! I am new to open source. May I work on this issue?

**Comment by harsh-the-innovator** [comment]
Hello! I am new to open source. I don't know where to start. Mai I work on this issue?

**Comment by bear217** [comment]
@rasmita404  I've assigned you to this  issue! it looks like you already have a pull request #37, so I will review it and see if it's ready to be merged!

**Comment by rasmita404** [comment]
Sure!!
