### ISSUE TITLE
Add a link to the Code of Conduct on the website

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#4]
Add a link to P2P Hack Club's Code of Conduct directly from the website: https://community.p2phack.club/CONDUCT.html.

---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by ysstudio22** [comment]
Hi James.  I’m Yoshi.  Love what you’re doing.  I’d like to work on this.

**Comment by thatrobotdev** [comment]
Hey @ysstudio22, it's nice to meet you! I've assigned you to the issue, thank you so much! Let me know if you need any help in any part of the process! :)

**Comment by thatrobotdev** [comment]
Maybe a good place would either be in the footer, or in one of the navigation pages! It's up to you though, whatever seems the best.

**Comment by ysstudio22** [comment]
Gotcha. 👍🏻 I'll take a look around the site.

**Comment by ysstudio22** [comment]
@manasvip01 Sorry, I already added the link and made a PR for it.

**Comment by manasvip01** [comment]
okay,no problem:))
