### ISSUE TITLE
Stylize footer to match colors + style

### ISSUE THREAD

**Issue by bear217** [P2PHackClub/website#40]
In the process of adding a ton of new and fun features to our website, the footer is becoming a bit busy. Using only CSS (don't change the content at all), stylize the footer of the page to match the rest of the colors on the page, and make it a bit more readable. Stylize it with the font that we have currently on the rest of the page! 

![image](https://user-images.githubusercontent.com/71842478/137516564-174163c9-33fb-40a0-9d47-f774aac1b052.png)

**This is a first-timers-only issue, which means that it is only intended for those who are new to open source/coding.**

**Comment by S3cBar0n** [comment]
@Sinbad07 This issue has been assigned to you as your PR was already accepted and merged.

@abhij1607 Feel free to comment on one of our other Issues marked with Status: Available and we will assign the issue to you. Sinbad07's PR was accepted as it was already submitted before we had time to assign this issue.


Thanks and Happy Hacking!
