### ISSUE TITLE
Extend description about Hacktoberfest 2021

### ISSUE THREAD

**Issue by thatrobotdev** [P2PHackClub/website#8]
Right now, the site has this description in the events area talking about Hacktoberfest:

> Hacktoberfest is an annual event that takes place every October in the spirit of open source and collaboration. For more information, Click Here!

This section can be updated to house more information about the event and talking more about how you can contribute to the website! For reference, this is what the README.md for the website currently states:

> ### Hacktoberfest
> ![Hacktoberfest 2021 Banner](https://user-images.githubusercontent.com/18013689/136124188-d4fb5a94-9361-49ef-b72c-94fe8b00f0e8.png)
> ![GitHub Hacktoberfest combined status](https://img.shields.io/github/hacktoberfest/2021/P2PHackClub/website)
> 
> Hello Hacktoberfest contributors! P2P Hack Club is participating in Hacktoberfest 2021 this year! If you didn't know, Hacktoberfest is an annual event for the month of October encouraging participation in the open source community. If you complete the 2021 challenge, you can learn a limited edition T-shirt. [For more information, you can check out the Hacktoberfest website here.](https://hacktoberfest.digitalocean.com)
> 
> #### How to help out P2P Hack Club and win a free T-Shirt!
> 
> **Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://kcd.im/pull-request).
> 
> Before you start, please read our [Code of Conduct](http://community.p2phack.club/CONDUCT.html).
> 
> 1. Choose one of our [participating repositories](https://github.com/P2PHackClub):
>       * **[P2PHackClub/website](https://github.com/P2PHackClub/website/)** - main website
>       * **[P2PHackClub/hypixel-game-night-website](https://github.com/P2PHackClub/hypixel-game-night-website)** - website for the HGN community event
>       * **[P2PHackClub/among-us-game-night-website](https://github.com/P2PHackClub/among-us-game-night-website)** - website for the AUGN community event
>       * **[P2PHackClub/community](https://github.com/P2PHackClub/community)** - all of P2P Hack Club's community documents
> 2. Look through the issues (in the issues tab), and find a feature to contribute/a bug to fix.
>       * **TIP:** Issues labeled [*"first-timers-only*](https://www.firsttimersonly.com) are for first time contributors. These issues are generally simple fixes to help you get the hang of the contribution process.
>       * If there aren't any issues, create one! There's always something to improve, even if someone hasn't asked for a specific improvement yet.
> 3. Address the issue by creating a pull request.
> 4. Submit the pull request for review.
> 5. Make any requested changes from project maintainers.
> 6. Booyah! Your PR is merged into the repository!

---

This is a _"first-timers-only"_ issue. That means that we are requesting that only those new to open source try this one out! Please ask as many questions as you need, I am here to help you create your first contribution to open-source :D

**Comment by obakeng-develops** [comment]
Hi, first timer. Could I please be assigned to this issue?

**Comment by S3cBar0n** [comment]
Hey @obakeng-develops!

Are you still working on this issue?
